#!/bin/bash

set -x -e

version=`cat csi-local-version/number`
pushd csi-local-volume-release

rm -rf .final_builds

bosh -n create-release --tarball=dev_releases/csi-local-volume/csi-local-volume-$version.tgz --version $version --name csi-local-volume --force
mv dev_releases/csi-local-volume/csi-local-volume-$version.tgz ../created-csi-local-volume-release/csi-local-volume-$version.tgz
popd
